import { getDatabase } from "../lib/mongodb"

const JOB_CATEGORIES = [
  {
    name: "Technology",
    subcategories: [
      "Software Development",
      "Web Development",
      "Mobile Development",
      "Data Science",
      "DevOps",
      "Cybersecurity",
      "UI/UX Design",
      "Quality Assurance",
      "Technical Support",
      "System Administration",
    ],
    skills: [
      "JavaScript",
      "Python",
      "Java",
      "React",
      "Node.js",
      "Angular",
      "Vue.js",
      "PHP",
      "C++",
      "C#",
      "Ruby",
      "Go",
      "Swift",
      "Kotlin",
      "Flutter",
      "MongoDB",
      "MySQL",
      "PostgreSQL",
      "Redis",
      "AWS",
      "Azure",
      "Docker",
      "Kubernetes",
      "Git",
      "Jenkins",
      "Linux",
      "Windows Server",
    ],
  },
  {
    name: "Customer Service",
    subcategories: [
      "Call Center",
      "Technical Support",
      "Sales Support",
      "Chat Support",
      "Email Support",
      "Field Service",
      "Customer Success",
      "Account Management",
    ],
    skills: [
      "Communication",
      "Problem Solving",
      "Active Listening",
      "Patience",
      "Empathy",
      "Multi-tasking",
      "CRM Software",
      "Zendesk",
      "Salesforce",
      "Microsoft Office",
      "Data Entry",
      "Typing Speed",
      "Phone Etiquette",
    ],
  },
  {
    name: "Sales & Marketing",
    subcategories: [
      "Inside Sales",
      "Field Sales",
      "Digital Marketing",
      "Content Marketing",
      "Social Media Marketing",
      "Email Marketing",
      "SEO/SEM",
      "Brand Management",
      "Market Research",
      "Business Development",
    ],
    skills: [
      "Sales",
      "Lead Generation",
      "Cold Calling",
      "Negotiation",
      "CRM",
      "Google Analytics",
      "Facebook Ads",
      "Google Ads",
      "SEO",
      "Content Writing",
      "Social Media",
      "Email Marketing",
      "Presentation",
      "Market Analysis",
    ],
  },
  {
    name: "Healthcare",
    subcategories: [
      "Nursing",
      "Medical Assistant",
      "Pharmacy",
      "Laboratory",
      "Radiology",
      "Physical Therapy",
      "Home Care",
      "Medical Administration",
      "Healthcare IT",
    ],
    skills: [
      "Patient Care",
      "Medical Knowledge",
      "CPR Certified",
      "First Aid",
      "Medical Terminology",
      "HIPAA Compliance",
      "Electronic Health Records",
      "Vital Signs",
      "Medication Administration",
      "Medical Equipment",
    ],
  },
  {
    name: "Construction",
    subcategories: [
      "General Labor",
      "Carpentry",
      "Electrical",
      "Plumbing",
      "Masonry",
      "Painting",
      "Roofing",
      "HVAC",
      "Heavy Equipment",
      "Site Supervision",
    ],
    skills: [
      "Construction",
      "Blueprint Reading",
      "Safety Protocols",
      "Hand Tools",
      "Power Tools",
      "Welding",
      "Electrical Work",
      "Plumbing",
      "Carpentry",
      "Heavy Machinery",
      "Project Management",
      "Quality Control",
    ],
  },
  {
    name: "Hospitality",
    subcategories: [
      "Hotel Management",
      "Restaurant Service",
      "Kitchen Staff",
      "Housekeeping",
      "Front Desk",
      "Event Management",
      "Tourism",
      "Food & Beverage",
      "Catering",
    ],
    skills: [
      "Customer Service",
      "Food Service",
      "Hospitality",
      "Communication",
      "Multitasking",
      "POS Systems",
      "Food Safety",
      "Cleaning",
      "Event Planning",
      "Language Skills",
      "Cultural Awareness",
    ],
  },
  {
    name: "Transportation",
    subcategories: [
      "Delivery Driver",
      "Truck Driver",
      "Taxi/Cab Driver",
      "Logistics",
      "Warehouse",
      "Courier Service",
      "Public Transport",
      "Fleet Management",
    ],
    skills: [
      "Driving",
      "Navigation",
      "Vehicle Maintenance",
      "Safety Compliance",
      "Customer Service",
      "Time Management",
      "GPS Systems",
      "Load Management",
      "Documentation",
      "Physical Fitness",
      "Route Planning",
    ],
  },
  {
    name: "Security",
    subcategories: [
      "Security Guard",
      "CCTV Monitoring",
      "Access Control",
      "Event Security",
      "Corporate Security",
      "Retail Security",
      "Cybersecurity",
      "Investigation",
    ],
    skills: [
      "Security",
      "Surveillance",
      "Alert",
      "Physical Fitness",
      "Communication",
      "Emergency Response",
      "Report Writing",
      "CCTV Operation",
      "Access Control",
      "Conflict Resolution",
      "First Aid",
      "Security Equipment",
    ],
  },
  {
    name: "Manufacturing",
    subcategories: [
      "Production Worker",
      "Quality Control",
      "Machine Operator",
      "Assembly Line",
      "Packaging",
      "Maintenance",
      "Warehouse",
      "Inventory Management",
    ],
    skills: [
      "Manufacturing",
      "Quality Control",
      "Machine Operation",
      "Assembly",
      "Safety Protocols",
      "Inventory Management",
      "Packaging",
      "Maintenance",
      "Technical Skills",
      "Attention to Detail",
      "Physical Stamina",
    ],
  },
  {
    name: "Education",
    subcategories: [
      "Teaching",
      "Tutoring",
      "Training",
      "Educational Administration",
      "Curriculum Development",
      "Student Support",
      "Educational Technology",
      "Special Education",
    ],
    skills: [
      "Teaching",
      "Communication",
      "Curriculum Development",
      "Classroom Management",
      "Educational Technology",
      "Assessment",
      "Student Engagement",
      "Patience",
      "Subject Matter Expertise",
      "Presentation Skills",
      "Mentoring",
    ],
  },
]

async function seedCategories() {
  try {
    const db = await getDatabase()

    // Create categories collection
    const categoriesCollection = db.collection("categories")

    // Clear existing categories
    await categoriesCollection.deleteMany({})

    // Insert new categories
    await categoriesCollection.insertMany(JOB_CATEGORIES)

    console.log("[v0] Job categories seeded successfully")
    console.log(`[v0] Created ${JOB_CATEGORIES.length} categories with subcategories and skills`)
  } catch (error) {
    console.error("[v0] Error seeding categories:", error)
    throw error
  }
}

// Run the seeding
seedCategories().catch(console.error)
